[build]
  publish = "public"
  command = "yarn build"
  functions = "functions"
[build.environment]
  NODE_VERSION = "12"
  YARN_VERSION = "1.22.10"
  YARN_FLAGS = "--no-ignore-optional"
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin= "*"
